speed: &speed
    2.4
inertial_frame_id: world
waypoints:
  -
    point: [70, 0, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [80, 80, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 100, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 0, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [80, 0, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [90, 90, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 100, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [-10, -10, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [90, -10, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [100, 100, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
