speed: &speed
    2.5
inertial_frame_id: world
waypoints:
  -
    point: [10, 40, -10]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 70, -10]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 150, -10]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [120, 200, -10]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [200, 220, -15]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [180, 270, -15]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
