speed: &speed
    2.4
inertial_frame_id: world
waypoints:
  -
    point: [40, 0, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [50, 50, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [150, 0, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [200, 120, -320]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [220, 200, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
  -
    point: [270, 180, -325]
    max_forward_speed: *speed
    heading: 0
    use_fixed_heading: False
